Book.id=3456
Book.title=Let Us C
Book.price=300
Book.authors=Kanetkar,Mayank


Student.sid=678
Student.sname=Anmol
Student.course=Java

Course.courseId=1
Course.courseName=Java
Course.courseCost=5000.0